kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregate:projects
  labels:
    rbac.authorization.k8s.io/aggregate-to-project-admin: "true"
# These rules will be added to the "project-admin" role.
rules:
- apiGroups: ["tutorial.harbur.io"]
  resources: ["projects"]
  verbs: ["*"]
