kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: users:namespace-rw
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules: []
