kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: users:namespace-admin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-namespace-admin: "true"
rules: []
